### ISSUE TITLE
Using image sequences / 3d images?

### ISSUE THREAD

**Issue by antithing** [Norman0406/OpenSkeletonFitting#5]
Hi, and thanks for making this code available. I am trying to run it on stored depth images, but can't quite figure it out. I see that `InputNumbered` tries to load a color frame, a depth frame AND a 3d frame? What is this 3d frame? 

Is there an example of using InputNumbered anywhere? Thank you!

**Comment by Norman0406** [comment]
Hi!
The 3D frame is basically a point cloud. It is represented as a three-channel floating point image, where the channels represent coordinates in X, Y and Z direction respectively. You can compute this 3D image from the depth map if you know the camera geometry.
Sorry, but there are no more examples except from what is inside this repo. This was a research project only.

**Comment by Norman0406** [comment]
I'll close this issue. Feel free to re-open if you have more questions.
